<?php

namespace AppBundle\Repository;

/**
 * SpeciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    public function finBySpecies($species, $user)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.animals', 'a')
            ->addSelect('a')
            ->where('a.user  = :user')
            ->andWhere('s.wording = :species')
            ->setParameter('user', $user)
            ->setParameter('species', $species)
            ->getQuery();
        return $qb->getResult();
    }

    public function findIdSpecies($tag)
    {
        $qb = $this->createQueryBuilder('s')
            ->select('s.id')
            ->where('s.wording = :tag')
            ->setParameter('tag', $tag)
            ->getQuery();
        return $qb->getOneOrNullResult();
    }

    public function getOneSpecies($tag)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.wording = :tag')
            ->setParameter('tag', $tag)
            ->getQuery();
        return $qb->getOneOrNullResult();
    }

    public  function coutAnimalBySpecies($tag)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.animals', 'a')
            ->select('a.id')
            ->where('s.wording = :tag')
            ->setParameter('tag', $tag)
            ->getQuery();

        return $qb->getResult();
    }
}
