<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getZipCode($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u.zipCode')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $qb->getOneOrNullResult();
    }

    public function getEmail($email)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u.email')
            ->where('u.email = :email')
            ->setParameter('email' , $email)
            ->getQuery();

        return $qb->getOneOrNullResult();
    }

    public function getUserMessages()
    {
        $qb = $this->createQueryBuilder('u')
            ->leftJoin('u.messages', 'm')
            ->addSelect('m.closed')
            ->where('m.closed = :false')
            ->setParameter('false', 0)
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function getUserAndMessages()
    {
        $qb = $this->createQueryBuilder('u')
            ->leftJoin('u.messages', 'm')
            ->addSelect('m')
            ->where('m.closed = :false')
            ->setParameter('false', 0)
            ->getQuery();
        return $qb->getResult();
    }
}
